@baseUrl = http://localhost:3000


### - Find All Products
GET {{baseUrl}}/

### --- add product
POST {{baseUrl}}/product
Authorization: yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOnsiZW1haWwiOiJmcmVkZXJpYy5ib3RlbGxhQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiRnJlZG91cmZzIiwiaWQiOjZ9LCJpYXQiOjE2NjMwNzM0NzQsImV4cCI6MTY2MzA3MzY1NH0.OvrQQg-RG580M-DOM1bETur91oVqQ_QUHysdu_f9r_s
Content-Type: application/json

{
    "title": "virginie@mail.io",
    "designation": "1234",
    "category": "Virginie",
    "url_image": "",
    "date_limit": "12/12/2022",
    "user_id": 1
}

### --- update product
POST {{baseUrl}}/product/2
Content-Type: application/json

{
    "title": "virginie@mail.i",
    "designation": "123465",
    "category": "Virginie",
    "url_image": "",
    "user_id": 1
}

### --- delete product
DELETE  {{baseUrl}}/product/11


### --- user login
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "frederic.botella@gmail.com",
    "password": "123465"
}
### --- user signup
POST {{baseUrl}}/signup
Content-Type: application/json

{
    "user_name": "Fred",
    "email": "frederic.botella@gmail.com",
    "password": "123465"
}

### --- user update
POST {{baseUrl}}/user/6
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOnsiZW1haWwiOiJmcmVkZXJpYy5ib3RlbGxhQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiRnJlZG91cmZzIiwiaWQiOjZ9LCJpYXQiOjE2NjMwNjk0OTIsImV4cCI6MTY2MzA2OTY3Mn0.oVLc_2mK-kGO7rfg4o91A0l74lEK1M2l9o6zX-VaNok
  
Content-Type: application/json

{
    "user_name": "Fredo",
    "email": "frederic.botella@gmail.com",
    "password": "123465"
}

### --- delete user
DELETE  {{baseUrl}}/user/3